TrajectoryNet:
  data:
    file_path: "dataset/dataset.csv"
    save_dir: "./checkpoints"

  model:
    input_size: 6
    hidden_size: 128
    output_size: 320
    dropout: 0.25

  training:
    name: "TrajectoryNet_7"
    batch_size: 256
    learning_rate: 0.001
    weight_decay: 1e-3
    num_epochs: 500
    early_stopping_patience: 500
    save_dir: "./checkpoints"

TrajectoryLSTM:
  input_size: 10
  hidden_size: 512
  num_layers: 3
  output_size: 4
  dropout: 0.2
  
  data:
    file_path: "dataset/lstm_dataset.csv"
    save_dir: "./checkpoints"

  training:
    batch_size: 80
    target_size: 4 
    input_size: 10
    seq_len: 80
    epochs: 1000
    learning_rate: 0.001


device: "cuda"

wandb: True
